services:
  - type: web
    name: ascii-image-converter
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn asciiserver.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ascii-image-converter.onrender.com
    healthCheckPath: /api/info/


